import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Dls Modas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <nav>
          <ul onclick="getElementById('close-menu').checked = false;">
            <li>
              <div class="tema">
                <label class="switch" for="theme">
                  <span class="switch-text">Tema</span>
                  <div class="switch-wrapper">
                    <input
                      class="input"
                      type="checkbox"
                      name="theme"
                      id="theme"
                    />
                    <span class="switch-button"></span>
                  </div>
                </label>
              </div>
            </li>
            <li>
              <a href="#sobre-mim">Sobre mim</a>
            </li>
            <li>
              <a href="#habilidades">Habilidades</a>
            </li>
            <li>
              <a href="#projetos">Projetos</a>
            </li>
            <li>
              <a href="#contatos">Contatos</a>
            </li>
          </ul>
        </nav>
      </main>
    </>
  );
}
